services:
  db_pg_mfi:
    image: postgres:14-alpine
    container_name: db_postgres_mfi
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: salman
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata_mfi:/var/lib/postgresql/data
volumes:
  pgdata_mfi: